markdown: kramdown
prose:
  siteurl: 'http://danielfdsilva.github.io/lego-box/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "base"
      - name: "energy_authority"
        field:
          element: "text"
          label: "Top energy authority"
      - name: "country_code"
        field:
          element: "select"
          label: "Coutry"
          placeholder: "Select country"
          options:
            - name: AF
              value: AFGHANISTAN
            - name: AL
              value: ALBANIA
            - name: DZ
              value: ALGERIA
            - name: AS
              value: AMERICAN SAMOA
            - name: AD
              value: ANDORRA
            - name: AO
              value: ANGOLA
            - name: AI
              value: ANGUILLA
            - name: AQ
              value: ANTARCTICA
            - name: AG
              value: ANTIGUA AND BARBUDA
            - name: AR
              value: ARGENTINA
