markdown: kramdown
prose:
  siteurl: 'http://danielfdsilva.github.io/lego-box/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "base"
      - name: "energy_authority"
        field:
          element: "text"
          label: "Top energy authority"
      - name: "country_code"
        field:
          element: "select"
          label: "Coutry"
          placeholder: "Select country"
          options:
            - name: AFGHANISTAN
              value: AF
            - name: ALBANIA
              value: AL
            - name: ALGERIA
              value: DZ
            - name: AMERICAN SAMOA
              value: AS
            - name: ANDORRA
              value: AD
            - name: ANGOLA
              value: AO
            - name: ANGUILLA
              value: AI
            - name: ANTARCTICA
              value: AQ
            - name: ANTIGUA AND BARBUDA
              value: AG
            - name: ARGENTINA
              value: AR
