markdown: kramdown
prose:
  siteurl: 'http://danielfdsilva.github.io/lego-box/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "base"
      - name: "size"
        field:
          element: "select"
          label: "Brick size"
          placeholder: "Select size"
          options:
            - name: "1 X 1"
              value: "1x1"
            - name: "2 X 2"
              value: "2x2"
            - name: "2 X 1"
              value: "2x1"
            - name: "3 X 1"
              value: "3x1"
            - name: "4 X 2"
              value: "4x2"
      - name: "color"
        field:
          element: "text"
          label: "Color"
